/**
 * Canonical DEMO-QA identifiers shared by seed replay, E2E fixtures, and design docs.
 * Auto-generated by `npm run demo:sync-seed` from fixtures/demo-workspace.sqlite — do not edit by hand.
 */
export const DEMO_QA_PROJECT_KEY = "DEMO-QA";
export const DEMO_QA_PROJECT_NAME = "Demo QA sample workspace";

/** Project-only workspace for E2E flows that need a blank slate (no pre-seeded entities). */
export const DEMO_QA_EMPTY_PROJECT_KEY = "DEMO-QA-EMPTY";
export const DEMO_QA_EMPTY_PROJECT_NAME = "Demo QA empty workspace";

export const DEMO_QA_REQUIREMENT_KEYS = {
  R1: "DEMO-R1",
  R2: "DEMO-R2",
  R3: "DEMO-R3"
} as const;

export const DEMO_QA_REQUIREMENT_TITLES = {
  R1: "User can create a project with a unique key",
  R2: "Archived projects are hidden from the default list",
  R3: "Overview KPI strip shows requirement, manual, and run counts"
} as const;

export const DEMO_QA_MANUAL_TITLES = {
  login: "Manual: User can create a project with a unique key",
  idleTimeout: "Manual: Archived projects are hidden from the default list",
  passwordReset: "Manual: Overview KPI strip shows requirement, manual, and run counts"
} as const;

export const DEMO_QA_AUTOMATED_TITLE = "API: project create returns stable key";

export const DEMO_QA_RUN_NAME = "Demo regression - staging";
export const DEMO_QA_PLAN_NAME = "Demo regression plan";

export const DEMO_QA_SEED_COUNTS = {
  requirements: 34,
  manualTestCases: 34,
  automatedTestCases: 6,
  plans: 1,
  planTestCases: 10,
  runTraceabilityEdges: 34
} as const;

export type DemoQaSeedManifest = {
  projectId: string;
  projectKey: string;
  requirementIds: Record<keyof typeof DEMO_QA_REQUIREMENT_KEYS, string>;
  manualTestCaseIds: Record<keyof typeof DEMO_QA_MANUAL_TITLES, string>;
  automatedTestCaseId: string;
  testPlanId: string;
  runId: string;
};

export type DemoQaEmptySeedManifest = {
  projectId: string;
  projectKey: string;
};

export type DemoQaWorkspaceManifest = {
  demoQa: DemoQaSeedManifest;
  demoQaEmpty: DemoQaEmptySeedManifest;
};
