/**
 * Shape of `fixtures/demo-qa-seed-data.json` — regenerated by `npm run demo:sync-seed`.
 * Used to replay DEMO-QA into empty databases (E2E bootstrap uses file copy instead).
 */
export const DEMO_QA_SEED_DATA_VERSION = 1 as const;

export type DemoQaSeedDataRequirement = {
  externalKey: string;
  title: string;
  description: string | null;
  releaseLabel: string | null;
  sprintLabel: string | null;
  status: string | null;
  priority: string | null;
  requirementType: string | null;
  tags: string[];
  parentExternalKey?: string;
};

export type DemoQaSeedDataManualTestCase = {
  title: string;
  releaseLabel: string | null;
  sprintLabel: string | null;
  requirementExternalKeys: string[];
  steps: Array<{ name: string; expectedResult: string | null }>;
};

export type DemoQaSeedDataAutomatedTestCase = {
  title: string;
  releaseLabel: string | null;
  sprintLabel: string | null;
  manualTitles: string[];
};

export type DemoQaSeedDataPlan = {
  name: string;
  description: string | null;
  releaseLabel: string | null;
  sprintLabel: string | null;
  testCaseTitles: string[];
};

export type DemoQaSeedDataRunResult = {
  testCaseTitle: string;
  status: "passed" | "failed" | "skipped" | "blocked" | "not_run";
  durationMs: number;
};

export type DemoQaSeedDataRun = {
  name: string;
  releaseLabel: string | null;
  sprintLabel: string | null;
  environment: string | null;
  buildVersion: string | null;
  trigger: string | null;
  results: DemoQaSeedDataRunResult[];
};

export type DemoQaSeedData = {
  version: typeof DEMO_QA_SEED_DATA_VERSION;
  exportedAt: string;
  project: {
    key: string;
    name: string;
    description: string | null;
  };
  requirements: DemoQaSeedDataRequirement[];
  manualTestCases: DemoQaSeedDataManualTestCase[];
  automatedTestCases: DemoQaSeedDataAutomatedTestCase[];
  plans: DemoQaSeedDataPlan[];
  runs: DemoQaSeedDataRun[];
};

/** E2E / fixture slot mapping derived from canonical external keys and links. */
export type DemoQaE2eSlots = {
  requirementKeys: { R1: string; R2: string; R3: string };
  requirementTitles: { R1: string; R2: string; R3: string };
  manualTitles: { login: string; idleTimeout: string; passwordReset: string };
  automatedTitle: string;
  planName: string;
  runName: string;
};
